export const ACTION_TYPE = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  SELECT_CONTENT:"SELECT_CONTENT",
  SEARCH_PRODUCT:"SEARCH_PRODUCT"
};